package local:importer;

world importer {
  record point {
    x: u32,
    y: u32,
  }
  import get-secret-word: func(num: u32, str: string) -> string;
  import get-number: func() -> u32;
  import get-list: func() -> list<string>;
  import get-point: func() -> point;
  import get-tuple: func() -> tuple<u32, string>;
  import maybe-get-number: func() -> result<u32, string>;
  import print: func(word: string);

  export print-or-error: func(msg: string) -> result<string, string>;
  export print-secret-word: func();
  export reveal-secret-word: func() -> string;
  export show-tuple: func() -> string;
  export maybe-return-number: func() -> result<u32, string>;
}
