package local:importer;

world importer {
  record point {
    x: u32,
    y: u32,
  }
  import get-secret-word: func(num: u32, str: string) -> string;
  import get-number: func() -> u32;
  import get-list: func() -> list<string>;
  import get-point: func() -> point;
  export reveal-secret-word: func() -> string;
}
