name: Elixir Compatibility

on:
  pull_request:
  push:
    branches:
      - main

env:
  MIX_ENV: test
  WASMEX_BUILD: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      fail-fast: false
      matrix:
        otp: [27.3.4.14, 28.5.0.3, 29.0.3]
        elixir: [1.18.4, 1.19.5, 1.20.2]
        exclude:
          - otp: 28.5.0.3
            elixir: 1.18.4
          - otp: 29.0.3
            elixir: 1.18.4
          - otp: 29.0.3
            elixir: 1.19.5
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Add targets
        run: |
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasip1

      - name: "Install cargo-component"
        run: cargo install --locked cargo-component
        shell: bash

      - run: mix do deps.get, deps.compile

      - run: mix test
