name: Rust CI

on:
  pull_request:
    paths:
      - "native/wasmex/**"
  push:
    branches:
      - main
    paths:
      - "native/wasmex/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./native/wasmex/

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.97.1
          components: rustfmt, clippy

      - name: Cache Rust build dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: native/wasmex

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run tests
        run: cargo test --all-targets --all-features

      - name: Run Clippy
        run: |
          touch src/lib.rs
          # need to disable extra_unused_lifetimes clippy because of rustler lifetime issues
          # https://github.com/rusterlium/rustler/issues/428
          cargo clippy --all-targets --all-features -- -D warnings -A clippy::extra_unused_lifetimes
